services:
  - type: web
    name: smmm-z-raporu
    runtime: docker
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: CF_API_TOKEN
        sync: false
      - key: CF_ZONE_ID
        sync: false
      - key: CF_ZONE_NAME
        value: gurcanekiz.xyz
